# Site settings
title: NahrWahr.io
description: A personal website for sharing thoughtful essays and analyses
url: "https://yourusername.github.io"
baseurl: ""
github_username: yourusername

# Build settings
markdown: kramdown
permalink: /:title/
exclude: [Gemfile, Gemfile.lock, README.md]

# Theme settings
show_excerpts: true
