# Site Settings
title: Your Name / Site Title          # Appears in the browser tab and header
description: >-                        # A short description for SEO and RSS
  A description of your personal website, focusing on analysis, essays, and work.
baseurl: ""                           # The subpath of your site, e.g. /blog. Usually leave empty for username.github.io
url: "https://yourusername.github.io" # The base hostname & protocol for your site
github_username: yourusername         # Optional: Your GitHub username
# twitter_username: yourusername      # Optional: Your Twitter username

# Build settings
# Theme: Choose a theme. 'minima' is a good, clean default.
# You can find more themes at https://rubygems.org/search?query=jekyll-theme
# Or browse https://jekyllthemes.io/, https://jamstackthemes.dev/ssg/jekyll/
theme: minima

# Plugins included with the github-pages gem
plugins:
  - jekyll-feed         # Creates an RSS feed (good practice)
  - jekyll-seo-tag    # Adds metadata tags for search engines
# - jekyll-gist       # Lets you embed GitHub Gists easily
# - jekyll-github-metadata # Accesses repo metadata

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - README.md
#   - LICENSE

# Optional: Setup default front matter for specific file types
defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "pages" # limit to pages (index.md, work.md, about.md)
    values:
      layout: "page" # Use the 'page' layout from the theme
  -
    scope:
      path: "_posts" # limit to files in _posts folder
      type: "posts"
    values:
      layout: "post" # Use the 'post' layout from the theme
