# Site settings
title: NahrWahr.io
description: A personal website for sharing thoughtful essays and analyses
url: "https://nahrwahr.github.io"
baseurl: "https://nahrwahr.github.io/PersonalSite/"
github_username: nahrwahr

# Build settings
markdown: kramdown
permalink: /:title/
exclude: [Gemfile, Gemfile.lock, README.md]

# Theme settings
show_excerpts: true
