# Replace placeholder values
title: NahrWahr.io  # Change from "Your Name / Site Title"
description: >-
  A personal website for sharing thoughtful essays, analysis, and reflections on topics I'm passionate about.
baseurl: ""
url: "https://nahrwahr.github.io"  # Adjust to your actual GitHub username
github_username: nahrwahr  # Update to your actual GitHub username

# Ensure the theme is properly set
theme: minima

# Make sure pagination is working properly
paginate: 5
paginate_path: "/page/:num/"
